### ISSUE TITLE
Category of Plagarism

### ISSUE THREAD

**Issue by yoedi** [riandyrn/owldetect#1]
Hello sir, 

I have question about category of plagarism, as you have mention at readme file, the categories are : 

    1. Students copy the exact phrases from other students homework
    2. Students copy then alter some words in the copied phrases
    3. Students copy only some phrases while also adding their own phrases

about no 2, Is it plagarism if the student altering some words in the middle of phrase? 
example : 

Input : My name is not John.
Ref : My name is John.

Altering "not" word before "John" count to be plagarism or not?

Thank you.

**Comment by riandyrn** [comment]
Hello, @yoedi 

We are not limiting the interpretation of plagiarism. It's up to you to interpret what plagiarism is.

We just give the basic constraints for the problem. For the rest, you need to figure it on your own.

This is part of the challenge. :)

**Comment by yoedi** [comment]
oke, I got it.
