### ISSUE TITLE
success respons

### ISSUE THREAD

**Issue by alffz** [riandyrn/owldetect#2]
what does the key and value array mean, and what is its purpose?

"start_idx": 0,
 "end_idx": 205

**Comment by riandyrn** [comment]
Can you try to guess what it is, @alffz? The clue is, it is related to selected string. 😃

**Comment by alffz** [comment]
I want to use machine learning for prediction , is it okey?

Pada tanggal Kam, 3 Feb 2022 22.57, Riandy Rahman Nugraha <
***@***.***> menulis:

**Comment by riandyrn** [comment]
You can do whatever you want, @alffz. 😃
